[platformio]
default_envs = teensy40

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
build_src_filter =
  +<*>
  -<roboclaw_address_scan.cpp>
build_flags =
  -std=gnu++17

[env:roboclaw_address_scan]
extends = env:teensy40
build_src_filter =
  -<*>
  +<RoboClaw.cpp>
  +<roboclaw_address_scan.cpp>
